### ISSUE TITLE
What is the NLL results with uniform dequantization?

### ISSUE THREAD

**Issue by zhengkw18** [Kim-Dongjun/UNCSN#4]
Hi, I found only the NLL results with variational dequantization in the big result table. Can you provide me with the results of uniform dequantization on CIFAR10 and IMAGENET32? Thanks a lot.

**Comment by Kim-Dongjun** [comment]
Hi!

3.03 for DDPM++ (VP, FID) + ST on CIFAR-10
3.90 for DDPM++ (VP, NLL) + ST on ImageNet32.

Thank you.
