### ISSUE TITLE
FFHQ 256

### ISSUE THREAD

**Issue by georgestein** [Kim-Dongjun/UNCSN#5]
Hi there,

For an ongoing study I would like to generate 100k FFHQ samples at 256 resolution with the model shown in Figure 15 of the paper and reported to get an FID of 5.54 here https://paperswithcode.com/sota/image-generation-on-ffhq-256-x-256.

Is this model publicly available? If not are you able to point me towards 50-100k generated images?

**Comment by Kim-Dongjun** [comment]
Hi, thank you for your interest to my paper.
Unfortunately, I deleted the project directory so there is no option that I can offer more,
Sorry for that :(

Best regards,
Dongjun Kim
